export const resourceCategories = [
  {
    id: 'widow',
    label: 'Widow Support',
    title: 'Widow & Grief Support Groups',
    description: 'Support groups and resources specifically for widows and those grieving the loss of a spouse.',
    keywords: ['widow', 'widower', 'spouse', 'husband', 'wife', 'grief', 'loss', 'bereavement', 'death', 'passed away', 'lost my husband', 'lost my wife'],
    resources: [
      {
        title: 'Hospice Family Care (Caring for Life)',
        type: 'Bereavement support',
        services: 'Adult bereavement groups (in-person). Madison Senior Center – 1st & 3rd Tuesdays. Huntsville/Madison County Senior Center – 2nd & 4th Wednesdays.',
        bestFor: 'Widows seeking ongoing support + structured program after loss',
        keywords: ['hospice', 'bereavement', 'grief', 'widow', 'senior', 'free', 'support group'],
      },
      {
        title: 'GriefShare - First Baptist Church',
        type: 'Faith-based grief support',
        services: 'Weekly faith-based healing sessions and discussion groups',
        bestFor: 'Widow-friendly, welcoming environment for grief recovery',
        website: 'https://www.griefshare.org/',
        keywords: ['griefshare', 'grief', 'baptist', 'church', 'faith', 'widow', 'support group', 'weekly'],
      },
      {
        title: 'GriefShare - Willowbrook Baptist Church',
        type: 'Faith-based grief support',
        services: 'Weekly faith-based healing sessions and discussion groups',
        bestFor: 'Widow-friendly, welcoming environment for grief recovery',
        website: 'https://www.griefshare.org/',
        keywords: ['griefshare', 'grief', 'baptist', 'church', 'faith', 'widow', 'support group', 'weekly'],
      },
      {
        title: 'GriefShare - Whitesburg Baptist Church',
        type: 'Faith-based grief support',
        services: 'Weekly faith-based healing sessions and discussion groups',
        bestFor: 'Widow-friendly, welcoming environment for grief recovery',
        website: 'https://www.griefshare.org/',
        keywords: ['griefshare', 'grief', 'baptist', 'church', 'faith', 'widow', 'support group', 'weekly'],
      },
      {
        title: 'GriefShare - Mayfair Church of Christ',
        type: 'Faith-based grief support',
        services: 'Weekly faith-based healing sessions and discussion groups',
        bestFor: 'Widow-friendly, welcoming environment for grief recovery',
        website: 'https://www.griefshare.org/',
        keywords: ['griefshare', 'grief', 'church of christ', 'faith', 'widow', 'support group', 'weekly'],
      },
      {
        title: 'Huntsville Hospital Grief Support',
        type: 'Community grief support',
        services: 'Adult grief support groups, specialized groups (loss of a child, etc.)',
        contact: '256-650-1212',
        bestFor: 'Those wanting structured, clinical grief support',
        keywords: ['huntsville', 'hospital', 'grief', 'support group', 'clinical', 'structured', 'widow'],
      },
      {
        title: 'Grief Recovery Method (Private Therapist-Led)',
        type: 'Small group therapy',
        services: 'Structured program to move through grief, led by licensed therapist',
        bestFor: 'Those wanting personal, guided support vs. open group sharing',
        keywords: ['grief recovery', 'therapist', 'therapy', 'small group', 'guided', 'widow', 'structured'],
      },
      {
        title: 'Survivors of Suicide Loss (SOS)',
        type: 'Specialized grief support',
        services: 'Monthly meetings at South Huntsville Library',
        bestFor: 'Those who have lost a loved one to suicide',
        keywords: ['suicide', 'loss', 'survivor', 'support group', 'monthly', 'grief'],
      },
      {
        title: 'GRASP (Grief Recovery After Substance Passing)',
        type: 'Specialized grief support',
        services: 'Meets 2nd & 4th Thursdays for those who lost someone to substance-related causes',
        bestFor: 'Those grieving a substance-related loss',
        keywords: ['grasp', 'substance', 'overdose', 'addiction', 'grief', 'support group'],
      },
    ],
  },
  {
    id: 'emotional',
    label: 'Emotional',
    title: 'Emotional & Mental Health Support',
    description: 'Support for grief, depression, anxiety, trauma, and isolation.',
    keywords: ['emotional', 'mental', 'health', 'grief', 'depression', 'anxiety', 'trauma', 'isolation', 'counseling', 'therapy', 'support', 'sad', 'stressed', 'overwhelmed', 'lonely', 'suicide', 'loss'],
    resources: [
      {
        title: 'Faith Chapel Christian Center',
        type: 'Biblical counseling',
        services: 'Free biblical counseling - spiritual and emotional support',
        bestFor: 'Grief, anxiety, depression, feeling unseen',
        keywords: ['faith', 'christian', 'biblical', 'counseling', 'grief', 'anxiety', 'depression', 'free'],
      },
      {
        title: 'Evangel Church PCA',
        services: 'Free confidential biblical counseling (weekly sessions)',
        website: 'https://www.evangelchurchpca.org/biblical-counseling',
        keywords: ['evangel', 'church', 'biblical', 'counseling', 'confidential', 'free'],
      },
      {
        title: 'Cornerstone Initiative - MEND',
        type: 'Trauma recovery and soul care',
        bestFor: 'Trauma survivors, PTSD, abuse recovery',
        website: 'https://www.cornerstone-al.org/initiatives',
        keywords: ['cornerstone', 'mend', 'trauma', 'ptsd', 'abuse', 'recovery', 'soul care'],
      },
      {
        title: 'Crisis Services of North Alabama',
        services: 'Local Domestic Violence Support Groups, Survivors of Suicide Loss Support Group, Protection from Abuse, Crisis Counseling, Housing Assistance',
        website: 'https://csna.org/',
        keywords: ['crisis', 'domestic violence', 'suicide', 'support group', 'counseling', 'housing', 'emergency', 'abuse'],
      },
      {
        title: 'Valley Christian Counseling',
        services: 'Income-based rates for counseling',
        website: 'https://www.valley-christiancounseling.com/',
        keywords: ['valley', 'christian', 'counseling', 'sliding scale', 'income-based', 'affordable'],
      },
      {
        title: 'HAPPI Health',
        services: 'Licensed counseling with sliding fees',
        website: 'https://www.happihealth.org/sliding-fee-scale-and-faqs',
        keywords: ['happi', 'health', 'counseling', 'sliding scale', 'licensed', 'affordable'],
      },
    ],
  },
  {
    id: 'spiritual',
    label: 'Spiritual',
    title: 'Spiritual & Existential Support',
    description: 'Prayer, spiritual direction, finding meaning and hope.',
    keywords: ['spiritual', 'prayer', 'faith', 'church', 'hope', 'meaning', 'purpose', 'god', 'religion', 'pastor', 'ministry'],
    resources: [
      {
        title: 'Impact Ministries',
        services: 'Spiritual growth, biblical teaching, online discipleship, community groups',
        website: 'https://impactministries.com/',
        keywords: ['impact', 'ministry', 'spiritual', 'discipleship', 'community', 'bible'],
      },
      {
        title: 'Local Church Pastoral Care',
        services: 'Prayer support, pastoral counseling, healing groups',
        bestFor: 'Loss of faith, wrestling with forgiveness',
        keywords: ['church', 'pastor', 'prayer', 'counseling', 'forgiveness', 'faith'],
      },
      {
        title: 'Church of the Highlands',
        services: 'Prayer teams',
        keywords: ['highlands', 'church', 'prayer'],
      },
      {
        title: 'First Baptist Church Oasis',
        services: 'Dementia CareGiver Support Group',
        website: 'https://fbchsv.org/oasis',
        keywords: ['baptist', 'oasis', 'dementia', 'caregiver', 'support group', 'alzheimers'],
      },
      {
        title: 'Grace Community Church',
        services: 'Mentoring',
        website: 'https://www.gcchsv.org/ministries',
        keywords: ['grace', 'community', 'church', 'mentoring'],
      },
      {
        title: 'Westminster Presbyterian',
        services: 'Guidance',
        keywords: ['westminster', 'presbyterian', 'guidance'],
      },
    ],
  },
  {
    id: 'safety',
    label: 'Safety',
    title: 'Safety & Protection',
    description: 'Emergency shelter, safe housing, protection from abuse.',
    keywords: ['safety', 'shelter', 'housing', 'abuse', 'domestic violence', 'homeless', 'emergency', 'protection', 'safe', 'escape'],
    resources: [
      {
        title: 'Downtown Rescue Mission',
        services: 'Overnight lodging, meals, case management, housing programs',
        website: 'https://downtownrescuemission.org/',
        keywords: ['downtown', 'rescue', 'mission', 'shelter', 'lodging', 'meals', 'housing', 'homeless'],
      },
      {
        title: 'New Futures',
        services: 'Shelter for homeless families with children',
        bestFor: 'Families fleeing unsafe situations',
        website: 'https://newfuturesinc.com/',
        keywords: ['new futures', 'shelter', 'families', 'children', 'homeless'],
      },
      {
        title: 'First Stop',
        services: 'Temporary housing, case management support, job placement assistance',
        website: 'https://firststop.org/',
        keywords: ['first stop', 'housing', 'temporary', 'case management', 'job', 'employment'],
      },
      {
        title: 'Huntsville Housing Authority',
        services: 'Housing assistance programs',
        website: 'https://hsvha.org/',
        keywords: ['huntsville', 'housing', 'authority', 'assistance', 'section 8', 'public housing'],
      },
      {
        title: 'Crisis Services of North Alabama',
        services: 'Local Domestic Violence Support Groups, Survivors of Suicide Loss Support Group, Protection from Abuse, Crisis Counseling, Housing Assistance',
        website: 'https://csna.org/',
        keywords: ['crisis', 'domestic violence', 'suicide', 'support group', 'counseling', 'housing', 'emergency', 'abuse'],
      },
      {
        title: 'Legal Services Alabama - DV',
        services: 'Protection orders, legal advocacy for abuse victims',
        contact: '866-456-4995',
        website: 'https://legalservicesalabama.org/',
        keywords: ['legal', 'domestic violence', 'protection order', 'abuse', 'advocacy'],
      },
    ],
  },
  {
    id: 'practical',
    label: 'Practical',
    title: 'Practical & Daily Living',
    description: 'Food, clothing, housing, transportation.',
    keywords: ['food', 'clothing', 'housing', 'transportation', 'rent', 'utilities', 'bills', 'groceries', 'hungry', 'eat', 'clothes'],
    resources: [
      {
        title: 'Huntsville Assistance Program',
        services: 'Emergency rent, utilities, and prescription assistance',
        website: 'https://huntsvilleap.org/',
        keywords: ['huntsville', 'assistance', 'rent', 'utilities', 'prescription', 'emergency', 'bills'],
      },
      {
        title: 'Food Bank of North Alabama',
        services: 'Food distribution and pantry network',
        website: 'https://www.foodbanknorthal.org/',
        keywords: ['food bank', 'food', 'pantry', 'groceries', 'hungry', 'eat'],
      },
      {
        title: 'Manna House',
        services: 'Hot meals and food assistance',
        website: 'https://www.mymannahouse.com/',
        keywords: ['manna', 'meals', 'food', 'hungry', 'eat', 'hot meals'],
      },
      {
        title: 'First Stop',
        services: 'Temporary housing, case management support, job placement assistance',
        website: 'https://firststop.org/',
        keywords: ['first stop', 'housing', 'temporary', 'case management', 'job', 'employment'],
      },
      {
        title: 'Huntsville Housing Authority',
        services: 'Housing assistance programs',
        website: 'https://hsvha.org/',
        keywords: ['huntsville', 'housing', 'authority', 'assistance', 'section 8', 'public housing'],
      },
      {
        title: 'Crisis Services of North Alabama',
        services: 'Local Domestic Violence Support Groups, Survivors of Suicide Loss Support Group, Protection from Abuse, Crisis Counseling, Housing Assistance',
        website: 'https://csna.org/',
        keywords: ['crisis', 'domestic violence', 'suicide', 'support group', 'counseling', 'housing', 'emergency', 'abuse'],
      },
      {
        title: 'Rose of Sharon Soup Kitchen',
        services: 'Meals and food assistance',
        website: 'https://roseofsharonsoupkitchen.org/',
        keywords: ['rose of sharon', 'soup kitchen', 'meals', 'food', 'hungry', 'eat'],
      },
      {
        title: 'Foodline',
        services: 'Food assistance ministry connecting families and individuals experiencing food emergencies to local church food pantries',
        contact: '256-534-2424',
        website: 'https://www.interfaithmissionservice.org/community-service/foodline/',
        keywords: ['foodline', 'food', 'pantry', 'emergency', 'hungry', 'groceries'],
      },
      {
        title: 'Salvation Army',
        services: 'Emergency assistance',
        keywords: ['salvation army', 'emergency', 'assistance'],
      },
    ],
  },
  {
    id: 'financial',
    label: 'Financial',
    title: 'Financial Stability',
    description: 'Budget help, debt relief, job training, emergency funds.',
    keywords: ['financial', 'money', 'budget', 'debt', 'job', 'employment', 'work', 'bills', 'income', 'broke', 'poor'],
    resources: [
      {
        title: 'Cornerstone Management',
        services: 'Financial coaching and budgeting classes',
        website: 'https://cornerstonemgt.net/',
        keywords: ['cornerstone', 'financial', 'coaching', 'budget', 'money'],
      },
      {
        title: 'The Cornerstone Initiative - Jobs For Life',
        services: 'Job readiness training and employment support',
        website: 'https://www.cornerstone-al.org/jobs-for-life',
        keywords: ['cornerstone', 'jobs', 'employment', 'training', 'work', 'career'],
      },
      {
        title: 'TEARS Foundation',
        services: 'Funeral assistance for families who have lost a child',
        website: 'https://thetearsfoundation.org/',
        keywords: ['tears', 'funeral', 'child loss', 'infant', 'baby', 'death', 'burial'],
      },
    ],
  },
  {
    id: 'legal',
    label: 'Legal',
    title: 'Legal & Advocacy',
    description: 'Legal aid, guardianship help, tenant rights.',
    keywords: ['legal', 'lawyer', 'attorney', 'court', 'guardianship', 'tenant', 'rights', 'eviction', 'custody'],
    resources: [
      {
        title: 'Legal Services Alabama',
        services: 'Free civil legal help for low-income residents',
        contact: '866-456-4995',
        website: 'https://legalservicesalabama.org/',
        keywords: ['legal', 'lawyer', 'free', 'civil', 'low-income'],
      },
      {
        title: 'Madison County Volunteer Lawyers',
        services: 'Pro bono legal assistance',
        contact: '256-539-2275',
        website: 'https://vlpmadisoncounty.org/',
        keywords: ['madison', 'volunteer', 'lawyer', 'pro bono', 'free', 'legal'],
      },
    ],
  },
  {
    id: 'parenting',
    label: 'Parenting',
    title: 'Parenting & Caregiving',
    description: 'Childcare, parenting classes, respite care.',
    keywords: ['parenting', 'childcare', 'daycare', 'children', 'kids', 'baby', 'preschool', 'caregiver'],
    resources: [
      {
        title: 'Public Pre-K Programs',
        services: 'Free preschool for qualifying families',
        keywords: ['pre-k', 'preschool', 'free', 'children', 'kids'],
      },
      {
        title: 'Community Action Partnership of North Alabama',
        services: 'Early childhood education and family support (Head Start)',
        website: 'https://capna.org/childrens-services/',
        keywords: ['head start', 'early childhood', 'education', 'family', 'children', 'kids'],
      },
      {
        title: 'DHR Child Care Subsidy',
        services: 'Financial assistance for childcare costs',
        website: 'https://dhr.alabama.gov/child-care/subsidy-overview/',
        keywords: ['dhr', 'childcare', 'subsidy', 'assistance', 'daycare', 'financial'],
      },
    ],
  },
  {
    id: 'health',
    label: 'Health',
    title: 'Health & Wellness',
    description: 'Healthcare access, chronic illness support, recovery.',
    keywords: ['health', 'healthcare', 'medical', 'doctor', 'illness', 'sick', 'recovery', 'addiction', 'disability'],
    resources: [
      {
        title: 'HAPPI Health',
        services: 'Behavioral health, medical services',
        bestFor: 'Chronic stress, sleep issues',
        website: 'https://www.happihealth.org/',
        keywords: ['happi', 'health', 'behavioral', 'medical', 'stress', 'sleep'],
      },
      {
        title: 'Alabama Dept. of Mental Health',
        services: 'Counseling, therapy, medical referrals',
        website: 'https://mh.alabama.gov/division-of-mental-health-substance-abuse-services/mental-illness-community-programs/',
        keywords: ['mental health', 'counseling', 'therapy', 'state', 'alabama'],
      },
      {
        title: 'Substance Abuse Recovery Programs',
        services: 'Recovery support and treatment',
        keywords: ['substance', 'abuse', 'addiction', 'recovery', 'drugs', 'alcohol', 'rehab'],
      },
      {
        title: 'Disability Support Services',
        services: 'Assistance for individuals with disabilities',
        keywords: ['disability', 'disabled', 'assistance', 'support'],
      },
      {
        title: 'Crisis Services of North Alabama',
        services: 'Local Domestic Violence Support Groups, Survivors of Suicide Loss Support Group, Protection from Abuse, Crisis Counseling, Housing Assistance',
        website: 'https://csna.org/',
        keywords: ['crisis', 'domestic violence', 'suicide', 'support group', 'counseling', 'housing', 'emergency', 'abuse'],
      },
    ],
  },
  {
    id: 'infertility',
    label: 'Infertility',
    title: 'Infertility Support',
    description: 'Fertility clinics, reproductive health, support groups.',
    keywords: ['infertility', 'fertility', 'ivf', 'pregnancy', 'baby', 'conceive', 'reproductive'],
    resources: [
      {
        title: 'Fertility Institute of North Alabama',
        services: 'Comprehensive fertility evaluation, IVF',
        website: 'https://fertilityalabama.com/',
        keywords: ['fertility', 'ivf', 'evaluation', 'infertility'],
      },
      {
        title: 'Alabama Women\'s Wellness',
        services: 'Reproductive health services',
        website: 'https://www.alabamawomenswellnesscenter.com/',
        keywords: ['women', 'wellness', 'reproductive', 'health'],
      },
      {
        title: 'Huntsville Hospital Women & Children',
        services: 'Comprehensive women\'s health, OB/GYN',
        website: 'https://www.hhwomenandchildren.org/',
        keywords: ['huntsville', 'hospital', 'women', 'children', 'obgyn', 'pregnancy'],
      },
      {
        title: 'Hope for Fertility Foundation',
        services: 'Treatment grants for fertility assistance',
        website: 'https://www.hopeforfertility.org/grant/',
        keywords: ['hope', 'fertility', 'grants', 'financial', 'ivf'],
      },
      {
        title: 'Baby Quest Foundation',
        services: 'IVF funding assistance',
        website: 'https://babyquestfoundation.org/',
        keywords: ['baby quest', 'ivf', 'funding', 'grants', 'financial'],
      },
      {
        title: 'Huntsville Infertility Support',
        services: 'Peer support group',
        keywords: ['huntsville', 'infertility', 'support group', 'peer'],
      },
    ],
  },
]

export const missionCards = [
  {
    icon: 'Heart',
    title: 'Widows',
    description: 'Support for those who have lost their spouse',
  },
  {
    icon: 'Users',
    title: 'Grandparents',
    description: 'Helping those raising grandchildren',
  },
  {
    icon: 'Smile',
    title: 'Children',
    description: 'Care for those who have lost parents',
  },
  {
    icon: 'UsersRound',
    title: 'Community',
    description: 'Anyone with nowhere else to turn',
  },
]

export const processSteps = [
  {
    number: 1,
    title: 'Safety',
    description: 'First, we ensure you have a safe place and your immediate needs are met.',
  },
  {
    number: 2,
    title: 'Stability',
    description: 'Next, we connect you with resources for housing, food, financial support.',
  },
  {
    number: 3,
    title: 'Restoration',
    description: 'Finally, we support your journey toward healing, purpose, and renewed hope.',
  },
]

export const needsOptions = [
  'Emotional',
  'Spiritual',
  'Safety',
  'Food/Housing',
  'Financial',
  'Legal',
  'Parenting',
  'Health',
  'Infertility',
  'Other',
]

export const ageRanges = [
  'Under 18',
  '18-24',
  '25-34',
  '35-44',
  '45-54',
  '55-64',
  '65+',
]
